// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA59hVuSKW_x_pnTOFXBRcodKqrUZMY_94',
    appId: '1:104732623249:web:329343fd8f883b5e241a30',
    messagingSenderId: '104732623249',
    projectId: 'zeuus-replica',
    authDomain: 'zeuus-replica.firebaseapp.com',
    storageBucket: 'zeuus-replica.firebasestorage.app',
    measurementId: 'G-6S3V2XD6W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZovkbHAHwcLwp9EPIYf6vEZGDKTRNZNY',
    appId: '1:104732623249:android:cf1bbbeefac9dcbb241a30',
    messagingSenderId: '104732623249',
    projectId: 'zeuus-replica',
    storageBucket: 'zeuus-replica.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdccGI83SDPHdB5S4huIQ7jXPSrA4Ypqk',
    appId: '1:104732623249:ios:87b548f8af77cb6e241a30',
    messagingSenderId: '104732623249',
    projectId: 'zeuus-replica',
    storageBucket: 'zeuus-replica.firebasestorage.app',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdccGI83SDPHdB5S4huIQ7jXPSrA4Ypqk',
    appId: '1:104732623249:ios:87b548f8af77cb6e241a30',
    messagingSenderId: '104732623249',
    projectId: 'zeuus-replica',
    storageBucket: 'zeuus-replica.firebasestorage.app',
    iosBundleId: 'com.example.dash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA59hVuSKW_x_pnTOFXBRcodKqrUZMY_94',
    appId: '1:104732623249:web:329343fd8f883b5e241a30',
    messagingSenderId: '104732623249',
    projectId: 'zeuus-replica',
    authDomain: 'zeuus-replica.firebaseapp.com',
    storageBucket: 'zeuus-replica.firebasestorage.app',
    measurementId: 'G-6S3V2XD6W0',
  );

}